const PROVIDERS_CONFIG = {
  groq: {
    label: 'Groq (ultra-rapide)',
    needsKey: 'GROQ_API_KEY',
    models: [
      { id: 'llama-3.3-70b-versatile', label: 'Llama 3.3 70B', free: true },
      { id: 'llama-3.1-8b-instant', label: 'Llama 3.1 8B', free: true },
    ],
    default: 'llama-3.3-70b-versatile',
    endpoint: 'https://api.groq.com/openai/v1/chat/completions',
    envKey: 'GROQ_API_KEY',
  },
  openrouter: {
    label: 'OpenRouter (tous modèles)',
    needsKey: 'OPENROUTER_API_KEY',
    models: [
      { id: 'meta-llama/llama-3.3-70b-instruct', label: 'Llama 3.3 70B', free: true },
      { id: 'deepseek/deepseek-chat', label: 'DeepSeek V3', free: true },
      { id: 'deepseek/deepseek-r1', label: 'DeepSeek R1', free: true },
      { id: 'google/gemini-2.5-flash-lite', label: 'Gemini 2.5 Flash Lite', free: true },
      { id: 'google/gemini-2.5-pro-exp-03-25', label: 'Gemini 2.5 Pro', free: true },
      { id: 'meta-llama/llama-4-scout', label: 'Llama 4 Scout (10M ctx)', free: true },
      { id: 'meta-llama/llama-4-maverick', label: 'Llama 4 Maverick', free: true },
      { id: 'anthropic/claude-sonnet-4', label: 'Claude Sonnet 4', free: false },
      { id: 'anthropic/claude-sonnet-4.5', label: 'Claude Sonnet 4.5', free: false },
      { id: 'openai/gpt-4o-mini', label: 'GPT-4o mini', free: true },
      { id: 'openai/gpt-4o-2024-11-20', label: 'GPT-4o', free: true },
      { id: 'qwen/qwen-2.5-coder-32b-instruct', label: 'Qwen 2.5 Coder 32B', free: true },
      { id: 'mistralai/mistral-small-3.1-24b-instruct', label: 'Mistral Small 3.1 24B', free: true },
    ],
    default: 'meta-llama/llama-3.3-70b-instruct',
    endpoint: 'https://openrouter.ai/api/v1/chat/completions',
    envKey: 'OPENROUTER_API_KEY',
  },
  cerebras: {
    label: 'Cerebras (2000+ tok/s)',
    needsKey: 'CEREBRAS_API_KEY',
    models: [
      { id: 'gpt-oss-120b', label: 'GPT-OSS 120B', free: true },
      { id: 'zai-glm-4.7', label: 'ZAI GLM 4.7', free: true },
    ],
    default: 'gpt-oss-120b',
    endpoint: 'https://api.cerebras.ai/v1/chat/completions',
    envKey: 'CEREBRAS_API_KEY',
  },
  mistral: {
    label: 'Mistral (1B tok/mois)',
    needsKey: 'MISTRAL_API_KEY',
    models: [
      { id: 'mistral-small-latest', label: 'Mistral Small', free: true },
      { id: 'mistral-large-latest', label: 'Mistral Large', free: true },
      { id: 'codestral-latest', label: 'Codestral', free: true },
    ],
    default: 'mistral-small-latest',
    endpoint: 'https://api.mistral.ai/v1/chat/completions',
    envKey: 'MISTRAL_API_KEY',
  },
  gemini: {
    label: 'Google Gemini (gratuit)',
    needsKey: 'GEMINI_API_KEY',
    models: [
      { id: 'gemini-2.5-flash', label: 'Gemini 2.5 Flash', free: true },
      { id: 'gemini-2.5-flash-lite', label: 'Gemini 2.5 Flash Lite', free: true },
    ],
    default: 'gemini-2.5-flash',
    endpoint: 'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions',
    envKey: 'GEMINI_API_KEY',
  },
  github: {
    label: 'GitHub Models (gratuit)',
    needsKey: 'GITHUB_TOKEN',
    models: [
      { id: 'gpt-4o-mini', label: 'GPT-4o mini', free: true },
      { id: 'gpt-4o', label: 'GPT-4o', free: true },
      { id: 'gpt-4o-mini-ptu', label: 'GPT-4o mini PTU', free: true },
      { id: 'DeepSeek-R1', label: 'DeepSeek R1', free: true },
      { id: 'DeepSeek-V3', label: 'DeepSeek V3', free: true },
      { id: 'Phi-3.5-MoE-instruct', label: 'Phi-3.5 MoE', free: true },
      { id: 'Mistral-large', label: 'Mistral Large', free: true },
      { id: 'AI21-Jamba-1.5-Mini', label: 'AI21 Jamba 1.5 Mini', free: true },
      { id: 'Cohere-command-r-plus-08-2024', label: 'Cohere Command R+', free: true },
      { id: 'Llama-3.3-70B-Instruct', label: 'Meta Llama 3.3 70B', free: true },
    ],
    default: 'gpt-4o-mini',
    endpoint: 'https://models.inference.ai.azure.com/chat/completions',
    envKey: 'GITHUB_TOKEN',
  },
};

module.exports = { PROVIDERS_CONFIG };
